// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that generates Instagram posts for products.
 *
 * - generateInstagramPost - A function that handles the post generation process.
 * - GenerateInstagramPostInput - The input type for the generateInstagramPost function.
 * - GenerateInstagramPostOutput - The return type for the generateInstagramPost function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateInstagramPostInputSchema = z.object({
  productName: z.string().describe('The name of the product.'),
  productDescription: z.string().describe('The description of the product.'),
  tags: z.array(z.string()).optional().describe('Optional tags associated with the product.'),
});
export type GenerateInstagramPostInput = z.infer<typeof GenerateInstagramPostInputSchema>;

const GenerateInstagramPostOutputSchema = z.object({
  post: z.string().describe('The generated Instagram post, including a fun 2-sentence caption and 3 trending hashtags.'),
});
export type GenerateInstagramPostOutput = z.infer<typeof GenerateInstagramPostOutputSchema>;

export async function generateInstagramPost(input: GenerateInstagramPostInput): Promise<GenerateInstagramPostOutput> {
  return generateInstagramPostFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateInstagramPostPrompt',
  input: {schema: GenerateInstagramPostInputSchema},
  output: {schema: GenerateInstagramPostOutputSchema},
  prompt: `You are a social media marketing expert specializing in handcrafted goods. Your task is to generate a fun and engaging Instagram post for an artisan's product.

Product Name: {{{productName}}}
Description: {{{productDescription}}}
{{#if tags}}Tags: {{#each tags}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}{{/if}}

Instructions:
1. Write a fun, 2-sentence caption that captures the essence of the product.
2. Provide 3 trending, relevant hashtags.
3. Combine them into a single post string.
`,
});

const generateInstagramPostFlow = ai.defineFlow(
  {
    name: 'generateInstagramPostFlow',
    inputSchema: GenerateInstagramPostInputSchema,
    outputSchema: GenerateInstagramPostOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
