// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that generates artisan biographies.
 *
 * - generateArtisanBio - A function that handles the artisan biography generation process.
 * - GenerateArtisanBioInput - The input type for the generateArtisanBio function.
 * - GenerateArtisanBioOutput - The return type for the generateArtisanBio function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateArtisanBioInputSchema = z.object({
  artisanName: z.string().describe('The name of the artisan.'),
  craftType: z.string().describe('The type of craft the artisan specializes in (e.g., pottery, weaving, jewelry).'),
  region: z.string().describe('The region or location where the artisan is based.'),
  style: z.string().describe('The unique style or techniques the artisan employs.'),
  background: z.string().describe('Information about the artisan, their background, and inspiration.'),
});
export type GenerateArtisanBioInput = z.infer<typeof GenerateArtisanBioInputSchema>;

const GenerateArtisanBioOutputSchema = z.object({
  bio: z.string().describe('A compelling biography for the artisan.'),
});
export type GenerateArtisanBioOutput = z.infer<typeof GenerateArtisanBioOutputSchema>;

export async function generateArtisanBio(input: GenerateArtisanBioInput): Promise<GenerateArtisanBioOutput> {
  return generateArtisanBioFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateArtisanBioPrompt',
  input: {schema: GenerateArtisanBioInputSchema},
  output: {schema: GenerateArtisanBioOutputSchema},
  prompt: `You are a skilled biographer specializing in crafting compelling narratives for artisans.

  Based on the information provided, create a captivating biography that highlights the artisan's unique skills, background, and artistic vision.

  Artisan Name: {{{artisanName}}}
  Craft Type: {{{craftType}}}
  Region: {{{region}}}
  Style: {{{style}}}
  Background Information: {{{background}}}

  Biography:`, 
});

const generateArtisanBioFlow = ai.defineFlow(
  {
    name: 'generateArtisanBioFlow',
    inputSchema: GenerateArtisanBioInputSchema,
    outputSchema: GenerateArtisanBioOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
