// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that suggests compelling product narratives for artisans.
 *
 * - suggestProductNarrative - A function that generates product narratives.
 * - SuggestProductNarrativeInput - The input type for the suggestProductNarrative function.
 * - SuggestProductNarrativeOutput - The return type for the suggestProductNarrative function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestProductNarrativeInputSchema = z.object({
  productName: z.string().describe('The name of the product.'),
  productDescription: z.string().describe('A detailed description of the product, including its materials, craftsmanship, and unique features.'),
  artisanBackground: z.string().describe('Information about the artisan, including their background, inspiration, and techniques.'),
});
export type SuggestProductNarrativeInput = z.infer<typeof SuggestProductNarrativeInputSchema>;

const SuggestProductNarrativeOutputSchema = z.object({
  narrative: z.string().describe('A compelling narrative about the product, suitable for engaging customers.'),
});
export type SuggestProductNarrativeOutput = z.infer<typeof SuggestProductNarrativeOutputSchema>;

export async function suggestProductNarrative(input: SuggestProductNarrativeInput): Promise<SuggestProductNarrativeOutput> {
  return suggestProductNarrativeFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestProductNarrativePrompt',
  input: {schema: SuggestProductNarrativeInputSchema},
  output: {schema: SuggestProductNarrativeOutputSchema},
  prompt: `You are a skilled marketing copywriter, adept at crafting engaging product narratives.

  Based on the information provided about the product and the artisan, create a compelling narrative that will resonate with customers and highlight the unique value of the product.

  Product Name: {{{productName}}}
  Product Description: {{{productDescription}}}
  Artisan Background: {{{artisanBackground}}}

  Narrative:`,
});

const suggestProductNarrativeFlow = ai.defineFlow(
  {
    name: 'suggestProductNarrativeFlow',
    inputSchema: SuggestProductNarrativeInputSchema,
    outputSchema: SuggestProductNarrativeOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
