// This is an autogenerated file from Firebase Studio.

import { config } from 'dotenv';
config();

import '@/ai/flows/generate-artisan-bio.ts';
import '@/ai/flows/suggest-product-narrative.ts';
import '@/ai/flows/generate-product-details.ts';
import '@/ai/flows/parse-search-query.ts';
import '@/ai/flows/generate-instagram-post.ts';
import '@/ai/flows/generate-growth-insights.ts';
